(module
  (func (export "emscripten_get_preloaded_image_data") (param i32 i32 i32) (result i32)
    (i32.const 0))
  (func (export "emscripten_get_callstack") (param i32 i32 i32) (result i32)
    (i32.const 0))
  (func (export "OSD_MemInfo_getModuleHeapLength") (result f64)
    (f64.const 0))
  (func (export "emscripten_notify_memory_growth") (param i32))
  (func (export "__syscall_faccessat") (param i32 i32 i32 i32) (result i32)
    (i32.const 0))
  (func (export "__syscall_chmod") (param i32 i32) (result i32)
    (i32.const 0))
  (func (export "occt_worker_cancelled") (result i32)
    (i32.const 0))
  (func (export "occt_worker_progress") (param f64)))
