// Generated from protocol/errors.json and protocol/operations.json.
#pragma once

#include <array>
#include <string_view>

namespace occt_worker {
inline constexpr std::string_view kProtocolVersion = "1.0.0";
enum class ErrorCode {
  ConstructionFailed,
  BooleanFailed,
  FilletFailed,
  TessellationFailed,
  ImportExportFailed,
  HealingFailed,
  Cancelled,
  InvalidHandle,
  InvalidArgs,
  OutOfMemory,
  KernelError,
  ProtocolError,
};
inline constexpr std::array<const char*, 161> kOperationNames = {
  "approximateCurveBSpline",
  "approximateSurfaceBSpline",
  "batch",
  "bbox",
  "beginScope",
  "booleanCommon",
  "booleanCut",
  "booleanFuse",
  "classifyPoint",
  "capabilities",
  "convertCurveToBSpline",
  "convertSurfaceToBSpline",
  "createBuffer",
  "curveContinuity",
  "curveControlData",
  "curveDomain",
  "curveGeometry",
  "cylindricalHole",
  "editCurveBSpline",
  "editSurfaceBSpline",
  "endScope",
  "evaluateCurve",
  "evaluateSurface",
  "exportBREP",
  "exportGLTF",
  "exportIGES",
  "exportIGESDocument",
  "exportOBJ",
  "exportPLY",
  "exportSTEP",
  "exportSTEPDocument",
  "exportVRML",
  "exportXCAF",
  "extendCurve",
  "extendSurface",
  "freeBuffer",
  "getSubShape",
  "getSubShapes",
  "distance",
  "diagnoseShape",
  "defeature",
  "draftAngle",
  "extremaCurveCurve",
  "extremaCurveSurface",
  "extremaSurfaceSurface",
  "extrude",
  "fillet",
  "fixShape",
  "generalFuse",
  "generalTransform",
  "getAdjacency",
  "glue",
  "hollow",
  "importBREP",
  "importGLTF",
  "importIGES",
  "importIGESDocument",
  "importOBJ",
  "importPLY",
  "importSTEP",
  "importSTEPDocument",
  "importSTL",
  "importVRML",
  "importXCAF",
  "inspectTolerances",
  "intersectCurveCurve",
  "intersectCurveSurface",
  "intersectSurfaceSurface",
  "isSameShape",
  "isValid",
  "makeBox",
  "makeCompSolid",
  "makeCompound",
  "makeCone",
  "makeCylinder",
  "makeEdgeArc",
  "makeEdgeBezier",
  "makeEdgeBSpline",
  "makeEdgeCircle",
  "makeEdgeEllipse",
  "makeEdgeHelix",
  "makeEdgeHyperbola",
  "makeEdgeLine",
  "makeEdgeOffset",
  "makeEdgeParabola",
  "makeFace",
  "makeFaceOnSurface",
  "makeHalfSpace",
  "makePolygon",
  "makeSurfaceBezier",
  "makeSurfaceBSpline",
  "makeSurfaceExtrusion",
  "makeSurfaceFace",
  "makeSurfaceFilling",
  "makeSurfaceOffset",
  "makeSurfaceRevolution",
  "makeSurfaceRuled",
  "makeShell",
  "makeSolidFromShell",
  "makeSphere",
  "makeTorus",
  "makeVertex",
  "makeWedge",
  "makeWire",
  "massProps",
  "middlePath",
  "loft",
  "localPrism",
  "localRevolution",
  "linearForm",
  "revolutionForm",
  "obb",
  "offsetShape",
  "offsetWire2D",
  "probeFormat",
  "projectPointCurve",
  "projectPointSurface",
  "release",
  "releaseAll",
  "reparameterizeCurve",
  "reparameterizeSurface",
  "reduceCurveDegree",
  "reduceSurfaceDegree",
  "revolve",
  "section",
  "sectionAnalysis",
  "projectHLR",
  "selectGeneralFuseCells",
  "setTolerance",
  "sew",
  "shapeType",
  "split",
  "stats",
  "sweepPipe",
  "surfaceContinuity",
  "surfaceControlData",
  "surfaceDomain",
  "surfaceGeometry",
  "surfaceIsoCurve",
  "sweepPipeShell",
  "tessellate",
  "tessellateEdges",
  "topologyCounts",
  "triangulationData",
  "replaceTriangulation",
  "validateTriangulation",
  "repairTriangulation",
  "transform",
  "trimCurve",
  "trimSurface",
  "unifySameDomain",
  "updateCurvePole",
  "updateSurfacePole",
  "batchTransformCopy",
  "exportSTL",
  "chamfer",
  "shapeUpgrade",
  "translate",
  "rotate",
  "scale",
  "mirror",
};
struct HistorySupportEntry { const char* operation; const char* support; };
inline constexpr std::array<HistorySupportEntry, 161> kHistorySupport = {{
  {"approximateCurveBSpline", "unsupported"},
  {"approximateSurfaceBSpline", "unsupported"},
  {"batch", "unsupported"},
  {"bbox", "unsupported"},
  {"beginScope", "unsupported"},
  {"booleanCommon", "full"},
  {"booleanCut", "full"},
  {"booleanFuse", "full"},
  {"classifyPoint", "unsupported"},
  {"capabilities", "unsupported"},
  {"convertCurveToBSpline", "unsupported"},
  {"convertSurfaceToBSpline", "unsupported"},
  {"createBuffer", "unsupported"},
  {"curveContinuity", "unsupported"},
  {"curveControlData", "unsupported"},
  {"curveDomain", "unsupported"},
  {"curveGeometry", "unsupported"},
  {"cylindricalHole", "full"},
  {"editCurveBSpline", "unsupported"},
  {"editSurfaceBSpline", "unsupported"},
  {"endScope", "unsupported"},
  {"evaluateCurve", "unsupported"},
  {"evaluateSurface", "unsupported"},
  {"extendCurve", "unsupported"},
  {"extendSurface", "unsupported"},
  {"extremaCurveCurve", "unsupported"},
  {"extremaCurveSurface", "unsupported"},
  {"extremaSurfaceSurface", "unsupported"},
  {"exportBREP", "unsupported"},
  {"exportGLTF", "unsupported"},
  {"exportIGES", "unsupported"},
  {"exportIGESDocument", "unsupported"},
  {"exportOBJ", "unsupported"},
  {"exportPLY", "unsupported"},
  {"exportSTEP", "unsupported"},
  {"exportSTEPDocument", "unsupported"},
  {"exportVRML", "unsupported"},
  {"exportXCAF", "unsupported"},
  {"freeBuffer", "unsupported"},
  {"getSubShape", "unsupported"},
  {"getSubShapes", "unsupported"},
  {"distance", "unsupported"},
  {"diagnoseShape", "unsupported"},
  {"defeature", "full"},
  {"draftAngle", "unsupported"},
  {"extrude", "full"},
  {"fillet", "full"},
  {"fixShape", "full"},
  {"generalFuse", "unsupported"},
  {"generalTransform", "full"},
  {"getAdjacency", "unsupported"},
  {"glue", "unsupported"},
  {"hollow", "unsupported"},
  {"importBREP", "unsupported"},
  {"importGLTF", "unsupported"},
  {"importIGES", "unsupported"},
  {"importIGESDocument", "unsupported"},
  {"importOBJ", "unsupported"},
  {"importPLY", "unsupported"},
  {"importSTEP", "unsupported"},
  {"importSTEPDocument", "unsupported"},
  {"importSTL", "unsupported"},
  {"importVRML", "unsupported"},
  {"importXCAF", "unsupported"},
  {"inspectTolerances", "unsupported"},
  {"intersectCurveCurve", "unsupported"},
  {"intersectCurveSurface", "unsupported"},
  {"intersectSurfaceSurface", "unsupported"},
  {"isSameShape", "unsupported"},
  {"isValid", "unsupported"},
  {"makeBox", "unsupported"},
  {"makeCompSolid", "unsupported"},
  {"makeCompound", "unsupported"},
  {"makeCone", "unsupported"},
  {"makeCylinder", "unsupported"},
  {"makeEdgeArc", "unsupported"},
  {"makeEdgeBezier", "unsupported"},
  {"makeEdgeBSpline", "unsupported"},
  {"makeEdgeCircle", "unsupported"},
  {"makeEdgeEllipse", "unsupported"},
  {"makeEdgeHelix", "unsupported"},
  {"makeEdgeHyperbola", "unsupported"},
  {"makeEdgeLine", "unsupported"},
  {"makeEdgeOffset", "unsupported"},
  {"makeEdgeParabola", "unsupported"},
  {"makeFace", "unsupported"},
  {"makeFaceOnSurface", "unsupported"},
  {"makeHalfSpace", "unsupported"},
  {"makePolygon", "unsupported"},
  {"makeSurfaceBezier", "unsupported"},
  {"makeSurfaceBSpline", "unsupported"},
  {"makeSurfaceExtrusion", "unsupported"},
  {"makeSurfaceFace", "unsupported"},
  {"makeSurfaceFilling", "unsupported"},
  {"makeSurfaceOffset", "unsupported"},
  {"makeSurfaceRevolution", "unsupported"},
  {"makeSurfaceRuled", "unsupported"},
  {"makeShell", "unsupported"},
  {"makeSolidFromShell", "unsupported"},
  {"makeSphere", "unsupported"},
  {"makeTorus", "unsupported"},
  {"makeVertex", "unsupported"},
  {"makeWedge", "unsupported"},
  {"makeWire", "unsupported"},
  {"massProps", "unsupported"},
  {"middlePath", "unsupported"},
  {"loft", "full"},
  {"localPrism", "unsupported"},
  {"localRevolution", "unsupported"},
  {"linearForm", "unsupported"},
  {"revolutionForm", "unsupported"},
  {"obb", "unsupported"},
  {"offsetShape", "unsupported"},
  {"offsetWire2D", "unsupported"},
  {"probeFormat", "unsupported"},
  {"projectPointCurve", "unsupported"},
  {"projectPointSurface", "unsupported"},
  {"projectHLR", "unsupported"},
  {"release", "unsupported"},
  {"releaseAll", "unsupported"},
  {"reparameterizeCurve", "unsupported"},
  {"reparameterizeSurface", "unsupported"},
  {"reduceCurveDegree", "unsupported"},
  {"reduceSurfaceDegree", "unsupported"},
  {"revolve", "full"},
  {"section", "unsupported"},
  {"sectionAnalysis", "unsupported"},
  {"selectGeneralFuseCells", "unsupported"},
  {"setTolerance", "unsupported"},
  {"sew", "full"},
  {"shapeUpgrade", "unsupported"},
  {"shapeType", "unsupported"},
  {"split", "unsupported"},
  {"stats", "unsupported"},
  {"surfaceControlData", "unsupported"},
  {"surfaceDomain", "unsupported"},
  {"surfaceContinuity", "unsupported"},
  {"surfaceGeometry", "unsupported"},
  {"surfaceIsoCurve", "unsupported"},
  {"sweepPipe", "full"},
  {"sweepPipeShell", "partial"},
  {"tessellate", "unsupported"},
  {"tessellateEdges", "unsupported"},
  {"topologyCounts", "unsupported"},
  {"triangulationData", "unsupported"},
  {"replaceTriangulation", "unsupported"},
  {"validateTriangulation", "unsupported"},
  {"repairTriangulation", "unsupported"},
  {"transform", "full"},
  {"trimCurve", "unsupported"},
  {"trimSurface", "unsupported"},
  {"unifySameDomain", "full"},
  {"updateCurvePole", "unsupported"},
  {"updateSurfacePole", "unsupported"},
  {"batchTransformCopy", "unsupported"},
  {"exportSTL", "unsupported"},
  {"chamfer", "full"},
  {"translate", "full"},
  {"rotate", "full"},
  {"scale", "full"},
  {"mirror", "full"},
}};
}
